services:

  activemq:
#    image: webcenter/activemq:5.14.3
    image: masstransit/activemq
    restart: "no"
    mem_limit: 512m
    environment:
      TZ: "Asia/Barnaul"
      TIME_ZONE: "Asia/Barnaul"
      ACTIVEMQ_ADMIN_LOGIN: "admin1"
      ACTIVEMQ_ADMIN_PASSWORD: "admin1"
      ACTIVEMQ_CONFIG_MINMEMORY: "512"
      ACTIVEMQ_CONFIG_MAXMEMORY: "512"
      ACTIVEMQ_USERS_saeed: saeedpassword
    volumes:
      - ./data:/data
      - ./log:/var/log/activemq
    ports:
      - "8161:8161"
      - "61616:61616"
      - "61613:61613"