services:
  demo-terracotta-server1:
    hostname: demo-terracotta-server1
    container_name: demo-terracotta-server1
#    image: terracotta/terracotta-server-oss:5.6.4
    image: softwareag/terracotta-server:10.15.0.2
    environment:
      - OFFHEAP_RESOURCE_SIZE=512
      - OFFHEAP_RESOURCE_UNIT=MB
      - OFFHEAP_RESOURCE_NAME=default-resource
      - ACCEPT_EULA=y

    ports:
      - 9410:9410