spring:
#    cache:
#      jcache:
#        config: classpath:ehcache.xml

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
          use_structured_entries: true
        javax:
          persistence:
            sharedCache:
              mode: ALL
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        generate_statistics: true
    show-sql: true

logging:
  level:
    org:
      hibernate:
        cache: trace